# Generated by Django 4.2.17 on 2025-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfoTable',
            fields=[
                ('act_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='活动id')),
                ('coop_id', models.CharField(max_length=64, verbose_name='商户ID')),
                ('type', models.CharField(max_length=64, verbose_name='活动类型: ongoing/past/new(入参可all)')),
                ('title_en', models.CharField(max_length=32, verbose_name='英文活动标题')),
                ('title_zh', models.CharField(max_length=32, verbose_name='中文活动标题')),
                ('pic', models.CharField(max_length=128, verbose_name='活动图片链接：注意图片大小/像素等')),
                ('loc_code', models.CharField(max_length=32, verbose_name='地区编码')),
                ('tag', models.CharField(max_length=32, verbose_name='活动自定义表示，属于Y-Club or others')),
                ('detail_en', models.CharField(max_length=256, verbose_name='英文活动详情描述')),
                ('detail_zh', models.CharField(max_length=256, verbose_name='中文活动详情描述')),
                ('is_recommend', models.IntegerField(verbose_name='1-推荐 0-不推荐（默认置0）')),
                ('price', models.FloatField(max_length=64, verbose_name='活动价格都以人民币存储')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
            ],
            options={
                'verbose_name': 'actInfo',
                'db_table': '活动信息表',
                'ordering': ['start_time'],
                'get_latest_by': 'start_time',
            },
        ),
        migrations.CreateModel(
            name='ActsMarkTable',
            fields=[
                ('act_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='活动id')),
                ('uid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('is_mark', models.IntegerField(verbose_name='收藏状态：0-未收藏；1-收藏')),
                ('mask_time', models.DateTimeField(verbose_name='收藏日期')),
            ],
            options={
                'verbose_name': 'userAct',
                'db_table': '活动收藏表',
                'ordering': ['mask_time'],
                'get_latest_by': 'mask_time',
            },
        ),
        migrations.CreateModel(
            name='AreaCodeTable',
            fields=[
                ('loc_code', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='地区编码')),
                ('eng_name', models.CharField(max_length=64, verbose_name='英文')),
                ('chn_name', models.CharField(max_length=64, verbose_name='中文')),
            ],
            options={
                'db_table': '地区编码表',
            },
        ),
        migrations.CreateModel(
            name='MerchantInfoTable',
            fields=[
                ('coop_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='商户ID')),
                ('type', models.CharField(max_length=64, verbose_name='商户类型: ')),
                ('pic', models.CharField(max_length=128, verbose_name='商户图片链接')),
                ('loc_code', models.CharField(max_length=32, verbose_name='地区编码')),
                ('name', models.CharField(max_length=16, verbose_name='商家名称')),
                ('wechatid', models.CharField(max_length=32, verbose_name='商家微信ID')),
                ('email', models.CharField(max_length=32, verbose_name='商家邮箱')),
                ('detail_en', models.CharField(max_length=256, verbose_name='英文活动详情描述')),
                ('detail_zh', models.CharField(max_length=256, verbose_name='中文活动详情描述')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
                ('register_time', models.DateTimeField(verbose_name='商户注册时间')),
            ],
            options={
                'verbose_name': 'merchInfo',
                'db_table': '商家信息表',
                'ordering': ['register_time'],
                'get_latest_by': 'register_time',
            },
        ),
        migrations.CreateModel(
            name='MerchantMaskTable',
            fields=[
                ('coop_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='商户id')),
                ('uid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('is_mark', models.IntegerField(verbose_name='收藏商家状态：0-未收藏；1-收藏')),
                ('mask_time', models.DateTimeField(verbose_name='收藏日期')),
            ],
            options={
                'verbose_name': 'userFav',
                'db_table': '商家收藏表',
                'ordering': ['mask_time'],
                'get_latest_by': 'mask_time',
            },
        ),
        migrations.CreateModel(
            name='UserInforTable',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='用户id')),
                ('name', models.CharField(max_length=16, verbose_name='用户名称')),
                ('level', models.CharField(max_length=4, verbose_name='会员等级')),
                ('exptime', models.DateTimeField(verbose_name='过期日期')),
                ('level_status', models.IntegerField(verbose_name='状态：0-已过期；1-正常')),
                ('wechat', models.CharField(max_length=32, verbose_name='微信ID')),
                ('pic', models.CharField(max_length=128, verbose_name='用户头像图片链接')),
                ('profile', models.CharField(max_length=256, verbose_name='用户个人简介')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱用户')),
                ('phone_no', models.CharField(max_length=32, verbose_name='电话号码')),
                ('location', models.CharField(max_length=256, verbose_name='用户地址')),
                ('register_time', models.DateTimeField(verbose_name='注册日期')),
            ],
            options={
                'verbose_name': 'userInfo',
                'db_table': '用户信息表',
                'ordering': ['register_time'],
                'get_latest_by': 'register_time',
            },
        ),
        migrations.CreateModel(
            name='UserOrderTable',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('uid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('act_id', models.CharField(max_length=64, verbose_name='活动ID')),
                ('coop_id', models.CharField(max_length=64, verbose_name='商户ID')),
                ('pay_time', models.DateTimeField(verbose_name='支付日期')),
                ('order_time', models.DateTimeField(verbose_name='下单日期')),
                ('exp_time', models.DateTimeField(verbose_name='过期时间: ???')),
                ('paymentid', models.CharField(max_length=128, verbose_name='支付ID：成功支付才存在，否则为空')),
                ('order_status', models.IntegerField(verbose_name='订单状态：1-未支付 2-支付成功 3-支付失败')),
            ],
            options={
                'verbose_name': 'userOrder',
                'db_table': '用户订单表',
                'ordering': ['pay_time'],
                'get_latest_by': 'pay_time',
            },
        ),
    ]
