# Generated by Django 4.2.17 on 2025-01-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfortable',
            name='level',
            field=models.IntegerField(verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='userordertable',
            name='exp_time',
            field=models.IntegerField(verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='userordertable',
            name='order_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='订单ID：32个字符内，只能是数字、大小写字母_-|*且在同一个商户号下唯一。'),
        ),
        migrations.AlterField(
            model_name='userordertable',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AlterField(
            model_name='userordertable',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付日期'),
        ),
    ]
