# Generated by Django 4.2.17 on 2025-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvTable',
            fields=[
                ('inv_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='约球id')),
                ('inviterId', models.CharField(max_length=100, verbose_name='邀请者用户id')),
                ('inviteeId', models.CharField(max_length=10, verbose_name='被邀者用户id')),
                ('matchTime', models.CharField(max_length=10, verbose_name='约球时间')),
                ('msg', models.CharField(max_length=10, verbose_name='约球信息')),
                ('place', models.CharField(max_length=10, verbose_name='约球地点')),
                ('status', models.CharField(max_length=10, verbose_name='状态 0-邀请中 1-已接受')),
                ('other', models.CharField(max_length=10, verbose_name='其他')),
                ('createTime', models.CharField(max_length=10, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'user_inv',
                'db_table': 'user_inv',
                'ordering': ['createTime'],
                'get_latest_by': 'createTime',
            },
        ),
        migrations.CreateModel(
            name='UserRatingLongTable',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='用户id')),
                ('tech_one', models.CharField(max_length=10, verbose_name='用户正手评分')),
                ('tech_two', models.CharField(max_length=10, verbose_name='反手评分')),
                ('tech_three', models.CharField(max_length=10, verbose_name='动作控点评分')),
                ('tech_four', models.CharField(max_length=10, verbose_name='切削评分')),
                ('tech_five', models.CharField(max_length=10, verbose_name='发球评分')),
                ('person_one', models.CharField(max_length=10, verbose_name='沟通评分')),
                ('person_two', models.CharField(max_length=10, verbose_name='时间观念评分')),
                ('person_three', models.CharField(max_length=10, verbose_name='竞技精神评分')),
                ('person_four', models.CharField(max_length=10, verbose_name='形象评分')),
                ('person_five', models.CharField(max_length=10, verbose_name='慷慨度评分')),
                ('n', models.CharField(max_length=10, verbose_name='评分记录总数')),
            ],
            options={
                'verbose_name': 'user_rating_long',
                'db_table': 'user_rating_long',
                'ordering': ['uid'],
                'get_latest_by': 'uid',
            },
        ),
        migrations.CreateModel(
            name='UserRatingShortTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100, verbose_name='用户id')),
                ('tech_one', models.CharField(max_length=10, verbose_name='用户正手评分')),
                ('tech_two', models.CharField(max_length=10, verbose_name='反手评分')),
                ('tech_three', models.CharField(max_length=10, verbose_name='动作控点评分')),
                ('tech_four', models.CharField(max_length=10, verbose_name='切削评分')),
                ('tech_five', models.CharField(max_length=10, verbose_name='发球评分')),
                ('person_one', models.CharField(max_length=10, verbose_name='沟通评分')),
                ('person_two', models.CharField(max_length=10, verbose_name='时间观念评分')),
                ('person_three', models.CharField(max_length=10, verbose_name='竞技精神评分')),
                ('person_four', models.CharField(max_length=10, verbose_name='形象评分')),
                ('person_five', models.CharField(max_length=10, verbose_name='慷慨度评分')),
                ('rating_time', models.CharField(max_length=64, verbose_name='评分时间')),
            ],
            options={
                'verbose_name': 'user_rating_short',
                'db_table': 'user_rating_short',
                'ordering': ['uid'],
                'get_latest_by': 'uid',
            },
        ),
        migrations.CreateModel(
            name='UserRatingTable',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='用户id')),
                ('tech_one', models.CharField(max_length=10, verbose_name='用户正手评分')),
                ('tech_two', models.CharField(max_length=10, verbose_name='反手评分')),
                ('tech_three', models.CharField(max_length=10, verbose_name='动作控点评分')),
                ('tech_four', models.CharField(max_length=10, verbose_name='切削评分')),
                ('tech_five', models.CharField(max_length=10, verbose_name='发球评分')),
                ('person_one', models.CharField(max_length=10, verbose_name='沟通评分')),
                ('person_two', models.CharField(max_length=10, verbose_name='时间观念评分')),
                ('person_three', models.CharField(max_length=10, verbose_name='竞技精神评分')),
                ('person_four', models.CharField(max_length=10, verbose_name='形象评分')),
                ('person_five', models.CharField(max_length=10, verbose_name='慷慨度评分')),
            ],
            options={
                'verbose_name': 'user_rating',
                'db_table': 'user_rating',
                'ordering': ['uid'],
                'get_latest_by': 'uid',
            },
        ),
        migrations.AlterModelOptions(
            name='userinfortable',
            options={'get_latest_by': 'register_time', 'ordering': ['register_time'], 'verbose_name': 'user_info'},
        ),
        migrations.RemoveField(
            model_name='userinfortable',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfortable',
            name='exptime',
        ),
        migrations.RemoveField(
            model_name='userinfortable',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userinfortable',
            name='level_status',
        ),
        migrations.RemoveField(
            model_name='userinfortable',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='userinfortable',
            name='wechat',
        ),
        migrations.AlterField(
            model_name='activityinfotable',
            name='type_en',
            field=models.CharField(max_length=64, verbose_name='英文活动类型名称'),
        ),
        migrations.AlterField(
            model_name='activityinfotable',
            name='type_zh',
            field=models.CharField(max_length=64, verbose_name='中文活动类型名称'),
        ),
        migrations.AlterField(
            model_name='userinfortable',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户名称'),
        ),
        migrations.AlterModelTable(
            name='userinfortable',
            table='user_info',
        ),
        migrations.CreateModel(
            name='UserFriendTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100, verbose_name='用户id')),
                ('friendId', models.CharField(max_length=100, verbose_name='好友id')),
                ('createTime', models.CharField(max_length=64, verbose_name='创建时间')),
                ('other', models.CharField(blank=True, max_length=256, null=True, verbose_name='其他')),
            ],
            options={
                'verbose_name': 'user_friend',
                'db_table': 'user_friend',
                'ordering': ['createTime'],
                'get_latest_by': 'createTime',
                'unique_together': {('userId', 'friendId')},
            },
        ),
    ]
